# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
        -   id: destroyed-symlinks
        -   id: end-of-file-fixer
        -   id: fix-byte-order-marker
        -   id: check-added-large-files
            args: ['--maxkb=1024']
        -   id: check-case-conflict
        -   id: check-executables-have-shebangs
        -   id: check-illegal-windows-names
        -   id: check-shebang-scripts-are-executable
        -   id: check-merge-conflict
        -   id: detect-private-key
        # -   id: check-json
        -   id: check-toml
        -   id: check-yaml

# -   repo: https://github.com/codingjoe/relint
#     rev: 1.2.1
#     hooks:
#         - id: relint

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.4.2
    hooks:
    -   id: python-safety-dependencies-check
        files: requirements.txt

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
        - id: isort
          name: isort (python)

# because our vscode config likes comments
# FIXME: make apply only to things we specifically know it should apply to
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5

# - repo: local
#   hooks:
#     - id: check-fixme-now
#       name: Check for "FIXME NOW" comments
#       language: pygrep
#       entry: '(?i)FIXME\s?NOW'
